### ISSUE TITLE
I can't make the plugin work

### ISSUE THREAD

**Issue by paulo-roger** [ergochat/ergo-ldap#5]
Hi, so I changed Dockerfile to include the plugin like this:
```Dockerfile
## build ergo binary
FROM docker.io/golang:1.23-alpine AS build-env

# Update and install required packages
RUN apk upgrade -U --force-refresh --no-cache && \
    apk add --no-cache --purge --clean-protected -l -u make git

# Clone Ergo source code
WORKDIR /go/src/github.com/ergochat/ergo
RUN git clone --branch stable https://github.com/ergochat/ergo.git . --depth=1

# Modify the default config file to not bind to localhost and use port 6667
RUN sed -i 's/^\(\s*\)\"127.0.0.1:6667\":.*$/\1":6667":/' default.yaml && \
    sed -i 's/^\s*\"\[::1\]:6667\":.*$//' default.yaml

# Compile Ergo server
RUN make install

# Clone the ergo-ldap plugin
WORKDIR /go/src/github.com/ergochat/ergo-ldap
RUN git clone https://github.com/ergochat/ergo-ldap.git . --depth=1

# Build the ergo-ldap plugin
RUN make

## build ergo container
FROM docker.io/alpine:3.19

# Metadata
LABEL maintainer="Daniel Oaks <daniel@danieloaks.net>, Daniel Thamdrup <dallemon@protonmail.com>" \
      description="Ergo is a modern, experimental IRC server written in Go"

# Standard ports listened on
EXPOSE 6667/tcp 6697/tcp

# Copy the built Ergo binary, configuration files, and plugin from the build-env stage
COPY --from=build-env /go/bin/ergo /ircd-bin/
COPY --from=build-env /go/src/github.com/ergochat/ergo/default.yaml /ircd-bin/
COPY --from=build-env /go/src/github.com/ergochat/ergo/distrib/docker/run.sh /ircd-bin/
COPY --from=build-env /go/src/github.com/ergochat/ergo/languages /ircd-bin/languages/
COPY --from=build-env /go/src/github.com/ergochat/ergo-ldap/ergo-ldap /ircd-bin/plugins/

# Running volume holding config file, database, certificates
VOLUME /ircd
WORKDIR /ircd

# Default MOTD
COPY --from=build-env /go/src/github.com/ergochat/ergo/ergo.motd /ircd/ergo.motd

# Launch script
ENTRYPOINT ["/ircd-bin/run.sh"]

```

Added this to the ircd.yaml:
```yml
    auth-script:
        enabled: true
        command: "/ircd-bin/plugins/ergo-ldap"
        # constant list of args to pass to the command; the actual authentication
        # data is transmitted over stdin/stdout:
        args: ["/ircd/ldap-config.yaml"]
        # should we automatically create users if the plugin returns success?
        autocreate: true
        # timeout for process execution, after which we send a SIGTERM:
        timeout: 9s
        # how long after the SIGTERM before we follow up with a SIGKILL:
        kill-timeout: 1s
    registration:
        # can users register new accounts for themselves? if this is false, operators with
        # the `accreg` capability can still create accounts with `/NICKSERV SAREGISTER`
        enabled: false
    require-sasl:
        # if this is enabled, all clients must authenticate with SASL while connecting.
        # WARNING: for a private server, you MUST set accounts.registration.enabled
        # to false as well, in order to prevent non-administrators from registering
        # accounts.
        enabled: true
```
But I get error account doesn't exist when I try to login.

The ldap is reachable from ergo container:
```sh
~ $ nc -zv lldap 3890
lldap (172.22.0.2:3890) open
```

I don't know how to debug anymore, I have set debug mode to ergo logging but nothing useful shows up, the browser console gave me the info that the account doesn't exist.
